mutation SimultaneousCreateJob($Job1: String!, $Job2: String!, $Job3: String!, $Key1: String, $Key2: String, $Key3: String) {
  job1: Enqueue(task: $Job1, key: $Key1) {
    id
    status
  }
  job2: Enqueue(task: $Job2, key: $Key2) {
    id
    status
  }
  job3: Enqueue(task: $Job3, key: $Key3) {
    id
    status
  }
}

mutation SimulateUnstableJob($Key: String) {
  Enqueue(task: "unstable-job", key: $Key) {
    id
    attempts
    status
  }
}

mutation RetryDeadJob($id: String!) {
  RetryDeadJob(id: $id) {
    id
    task
    status
    attempts
  }
}

query GetAllJobs {
  Jobs {
    id
    task
    status
  }
}

query GetJobById($id: String!) {
  Job(id: $id) {
    id
    task
    status
    attempts
  }
}

query GetJobsByStatus($status: String!) {
  JobsByStatus(status: $status) {
    id
    task
    status
    attempts
  }
}

query GetAllJobStatus{
   JobStatus{
    pending
    running
    failed
    completed
    dead
  }
}